<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Chorus.App</RootNamespace>
    <AssemblyName>Chorus</AssemblyName>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" Version="2.1.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Speech" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chorus.Core\Chorus.Core.csproj" />
  </ItemGroup>

</Project>
