using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

namespace Chorus.Core.WakeWord;

/// <summary>Wake-word behaviour settings (surfaced in chorus.json + env).</summary>
public sealed record WakeWordSettings(
    string Phrase,
    bool Enabled,
    float Sensitivity,
    int CooldownMs,
    int SessionIdleMs)
{
    public static WakeWordSettings Default { get; } = new(
        Phrase: "hey chorus",
        Enabled: true,
        Sensitivity: 0.4f,     // threshold 0.34: all measured true <=0.30, near-misses >=0.35
        CooldownMs: 2000,
        SessionIdleMs: 45000);
}

/// <summary>Raised when the wake phrase is heard.</summary>
public sealed record WakeWordTrigger(DateTime Timestamp, string Phrase, float Score, int Hop, int TemplateCount);

/// <summary>Observable engine statistics (for the console/tray status).</summary>
public sealed record WakeWordStats(long HopsProcessed, int Triggers, float LastScore, double LastRms);

/// <summary>
/// The CHORUS wake-word engine: continuous 16 kHz int16 PCM in, 'wake'
/// events out. Pipeline (all on the calling thread — the NAudio capture
/// thread in the app):
///
///   320-sample mic frames -> sample buffer -> 400-sample windows every
///   160 samples (10 ms hops) -> MFCC (c1..c13, L2-normalized) -> multi-
///   template banded online DTW -> freshness window -> sensitivity
///   threshold -> cooldown -> <see cref="WakeDetected"/>.
///
/// Mute: while <see cref="Muted"/> is true the alignment advances but no
/// match-checking happens, so no events fire (and the app additionally
/// stops feeding frames entirely while muted — belt and braces).
///
/// Templates are packaged with the app as embedded resources
/// (Chorus.Core.WakeWord.Resources.*.mfc), generated by
/// tests/wakeword_templates.py against the Python reference DSP.
/// </summary>
public sealed class WakeWordEngine
{
    private readonly MfccExtractor _mfcc = new();
    private readonly List<OnlineDtw> _matchers = new();
    private readonly List<float[][]> _templates = new();
    private readonly Queue<(int Hop, float Cost)> _recent = new();
    private readonly List<short> _samples = new();

    private long _hopsProcessed;
    private int _triggers;
    private float _lastScore = float.PositiveInfinity;
    private double _lastRms;
    private long _lastTriggerMs = -86_400_000L; // 24 h ago: first trigger always passes the cooldown check
    private int _silentHops;
    private WakeWordSettings _settings;

    /// <summary>Raised on the feeding thread when the wake phrase is detected.</summary>
    public event Action<WakeWordTrigger>? WakeDetected;

    public WakeWordEngine(WakeWordSettings settings, IEnumerable<float[][]> templates)
    {
        _settings = settings;
        Enabled = settings.Enabled;
        foreach (var t in templates)
        {
            _templates.Add(t);
            _matchers.Add(new OnlineDtw(t));
        }
        if (_matchers.Count == 0)
            throw new ArgumentException("at least one template is required", nameof(templates));
    }

    /// <summary>Load the packaged templates and build the default engine.</summary>
    public static WakeWordEngine LoadDefault(WakeWordSettings? settings = null)
    {
        var templates = LoadEmbeddedTemplates();
        if (templates.Count == 0)
            throw new InvalidOperationException("no embedded wake-word templates found — is Chorus.Core built with the Resources?");
        return new WakeWordEngine(settings ?? WakeWordSettings.Default, templates);
    }

    public string Phrase => _settings.Phrase;

    /// <summary>Number of packaged acoustic templates (for status display).</summary>
    public int TemplateCount => _templates.Count;

    /// <summary>Master switch: wake listening on/off (app sets from config + UI).</summary>
    public bool Enabled { get; set; } = true;

    /// <summary>While muted, no wake events are emitted (frames may still be fed).</summary>
    public bool Muted { get; set; }

    /// <summary>0..1 — higher triggers more easily (more false positives).</summary>
    public float Sensitivity
    {
        get => _settings.Sensitivity;
        set => _settings = _settings with { Sensitivity = Math.Clamp(value, 0f, 1f) };
    }

    /// <summary>Minimum gap between triggers (double-trigger suppression).</summary>
    public int CooldownMs
    {
        get => _settings.CooldownMs;
        set => _settings = _settings with { CooldownMs = Math.Max(0, value) };
    }

    public WakeWordStats Stats => new(_hopsProcessed, _triggers, _lastScore, _lastRms);

    /// <summary>
    /// Feed one 320-sample (20 ms) 16 kHz mono frame. The engine buffers to
    /// the 10 ms hop internally. Cheap: ~1 FFT + ~26 filters + 13-pt DCT +
    /// one DTW column per template per hop.
    /// </summary>
    public void FeedFrame(ReadOnlySpan<short> frame)
    {
        if (!Enabled || frame.Length == 0) return;
        _samples.AddRange(frame.ToArray());

        while (_samples.Count >= WakeWordParams.WinLen)
        {
            var window = _samples.Take(WakeWordParams.WinLen).ToArray();
            _samples.RemoveRange(0, WakeWordParams.Hop);
            Step(window);
        }
    }

    public void Reset()
    {
        foreach (var m in _matchers) m.Reset();
        _samples.Clear();
        _recent.Clear();
        _silentHops = 0;
    }

    // -- pipeline ----------------------------------------------------------

    private void Step(short[] window)
    {
        var x = _mfcc.Compute(window);
        double rms = MfccExtractor.WindowRms(window);
        _lastRms = rms;
        int hop = (int)_hopsProcessed;

        bool voiced = rms >= WakeWordParams.EnergyFloor;
        if (rms >= WakeWordParams.OnsetFloor)
        {
            if (_silentHops >= WakeWordParams.MinSilenceHops)
            {
                // a new utterance started after a real pause: restart the
                // alignments so the DTW never absorbs leading silence — but
                // only after >=250 ms of quiet, so the natural inter-word
                // pause inside "hey chorus" does NOT split the phrase
                foreach (var m in _matchers) m.Reset();
                _recent.Clear();
            }
            _silentHops = 0;
        }
        else
        {
            _silentHops++;
        }

        if (Muted || !voiced)
        {
            // keep the alignment continuous; no match-checking while muted
            // or in near-silence (DTW cost stays high there anyway)
            foreach (var m in _matchers) m.Step(x);
            _recent.Enqueue((hop, float.PositiveInfinity));
        }
        else
        {
            float best = float.PositiveInfinity;
            foreach (var m in _matchers)
            {
                float c = m.Step(x);
                if (c < best) best = c;
            }
            _recent.Enqueue((hop, best));
        }

        while (_recent.Count > 0 && _recent.Peek().Hop <= hop - WakeWordParams.FreshnessHops)
            _recent.Dequeue();

        // earliest hop in the freshness window below the threshold = the
        // moment the phrase finished matching
        long nowMs = (long)hop * WakeWordParams.Hop * 1000L / WakeWordParams.SampleRate;
        foreach (var (h, cost) in _recent)
        {
            if (cost < WakeWordParams.SensitivityToThreshold(_settings.Sensitivity))
            {
                if (nowMs - _lastTriggerMs >= _settings.CooldownMs)
                {
                    _lastTriggerMs = nowMs;
                    _triggers++;
                    _lastScore = cost;
                    WakeDetected?.Invoke(new WakeWordTrigger(
                        DateTime.UtcNow, _settings.Phrase, cost, h, _templates.Count));
                }
                // whether fired or cooldown-suppressed, the phrase was said —
                // consume it so the NEXT phrase can match fresh
                Reset();
                break;
            }
        }

        _hopsProcessed++;
    }

    // -- packaged model ----------------------------------------------------

    private const string TemplateMagic = "CHMFC010";

    /// <summary>Read all embedded .mfc templates (see wakeword_lib.save_template).</summary>
    public static List<float[][]> LoadEmbeddedTemplates()
    {
        var result = new List<float[][]>();
        var asm = typeof(WakeWordEngine).Assembly;
        foreach (var name in asm.GetManifestResourceNames().Where(n => n.EndsWith(".mfc", StringComparison.Ordinal)))
        {
            using var stream = asm.GetManifestResourceStream(name)
                ?? throw new InvalidOperationException($"resource {name} missing");
            result.Add(ReadTemplate(stream, name));
        }
        return result;
    }

    private static float[][] ReadTemplate(Stream stream, string name)
    {
        using var reader = new BinaryReader(stream, Encoding.UTF8, leaveOpen: true);
        var magic = new string(reader.ReadChars(8));
        if (magic != TemplateMagic)
            throw new InvalidDataException($"bad template magic {magic} in {name}");
        int dim = reader.ReadInt32();
        int frames = reader.ReadInt32();
        if (dim != WakeWordParams.NMfcc || frames <= 0 || frames > 10000)
            throw new InvalidDataException($"bad template header {name}: dim={dim} frames={frames}");
        var data = new float[frames][];
        for (int i = 0; i < frames; i++)
        {
            var row = new float[dim];
            for (int k = 0; k < dim; k++)
                row[k] = reader.ReadSingle();
            data[i] = row;
        }
        return data;
    }

    /// <summary>Load an embedded raw int16 PCM sample (the canonical utterance).</summary>
    public static short[] LoadEmbeddedPcm(string resourceName)
    {
        var asm = typeof(WakeWordEngine).Assembly;
        using var stream = asm.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"resource {resourceName} missing");
        using var reader = new BinaryReader(stream);
        var bytes = reader.ReadBytes((int)stream.Length);
        var pcm = new short[bytes.Length / 2];
        for (int i = 0; i < pcm.Length; i++)
            pcm[i] = BitConverter.ToInt16(bytes, i * 2);
        return pcm;
    }

    public static string[] EmbeddedResourceNames() =>
        typeof(WakeWordEngine).Assembly.GetManifestResourceNames()
            .Where(n => n.StartsWith("Chorus.Core.WakeWord", StringComparison.Ordinal))
            .ToArray();
}
